using System;
using System.Collections.Generic;

namespace IrmaQuicDashboard.Models.Entities
{
    /// <summary>
    /// A single irma session logged to app and server
    /// </summary>
    public class IrmaSession
    {
        public Guid Id { get; set; }

        public Guid SessionUploadMetadataId { get; set; }

        /// <summary>
        /// External Id generated by the app, alternate key
        /// </summary>
        public int AppSessionId { get; set; }

        /// <summary>
        /// Session token, which is part of the QR Code path
        /// </summary>
        public string SessionToken { get; set; }

        /// <summary>
        /// Session token, which is generated by the requestor (Irmajs)
        /// </summary>
        public string IrmaJsSessionToken { get; set; }

        public DateTime Timestamp { get; set; }

        public List<IrmaAppLogEntry> AppLogEntries { get; set; }
        public List<IrmaServerLogEntry> ServerLogEntries { get; set; }
        public List<TimestampedLocation> TimestampedLocations { get; set; }
    }
}
